/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aplicacion;

import Persistencia.conexionOracle;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    static conexionOracle co = null;

    public VentanaPrincipal() {
        try {
            co = new conexionOracle();
            initComponents();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
            System.exit(1);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        etiquetaUsuario = new java.awt.TextField();
        jLabel2 = new javax.swing.JLabel();
        etiquetaPassword = new javax.swing.JPasswordField();
        buttonConfirmar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        conexion = new javax.swing.JMenu();
        itemSalir = new javax.swing.JMenuItem();
        expertoMenu = new javax.swing.JMenu();
        itemExperto = new javax.swing.JMenuItem();
        casosMenu = new javax.swing.JMenu();
        jMenuVerCasos = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuColaboracion = new javax.swing.JMenu();
        accionColabora = new javax.swing.JMenuItem();
        gestionCompleta = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("User");

        etiquetaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etiquetaUsuarioActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Password");

        buttonConfirmar.setText("Ok");

        conexion.setText("Conexión");

        itemSalir.setText("Salir de la Aplicación");
        itemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSalirActionPerformed(evt);
            }
        });
        conexion.add(itemSalir);

        jMenuBar1.add(conexion);

        expertoMenu.setText("Experto");

        itemExperto.setText("Gestión de Expertos");
        itemExperto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemExpertoActionPerformed(evt);
            }
        });
        expertoMenu.add(itemExperto);

        jMenuBar1.add(expertoMenu);

        casosMenu.setText("Casos Policiales");
        casosMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casosMenuActionPerformed(evt);
            }
        });

        jMenuVerCasos.setText("Ver Casos");
        jMenuVerCasos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuVerCasosActionPerformed(evt);
            }
        });
        casosMenu.add(jMenuVerCasos);

        jMenuBar1.add(casosMenu);
        jMenuBar1.add(jMenu4);

        menuColaboracion.setText("Colaboraciones");
        menuColaboracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuColaboracionActionPerformed(evt);
            }
        });

        accionColabora.setText("Mostrar");
        accionColabora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accionColaboraActionPerformed(evt);
            }
        });
        menuColaboracion.add(accionColabora);

        jMenuBar1.add(menuColaboracion);

        gestionCompleta.setText("Gestión Completa");

        jMenuItem1.setText("Comenzar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        gestionCompleta.add(jMenuItem1);

        jMenuBar1.add(gestionCompleta);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonConfirmar)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(etiquetaPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(etiquetaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiquetaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(etiquetaPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonConfirmar)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalirActionPerformed

        try {
            //co = new conexionOracle();
            co.desconexion();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } catch (Exception ex) {
            System.out.println("Error al conectar con el servidor: " + ex.getMessage());
        } finally {
            this.dispose();
        }
    }//GEN-LAST:event_itemSalirActionPerformed

    private void itemExpertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemExpertoActionPerformed
        try {
            // TODO add your handling code here:
            new VentanaExpertos(co).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_itemExpertoActionPerformed
    private void casosMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casosMenuActionPerformed
        try {
            // TODO add your handling code here:
            new VentanaColaboracion(co).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_casosMenuActionPerformed


    private void jMenuVerCasosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuVerCasosActionPerformed
        try {
            // TODO add your handling code here:
            new VentanaCasosPoliciales(co).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuVerCasosActionPerformed

    private void menuColaboracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuColaboracionActionPerformed

        try {
            new VentanaColaboracion(co).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_menuColaboracionActionPerformed

    private void accionColaboraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accionColaboraActionPerformed
        try {
            new VentanaColaboracion(co).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_accionColaboraActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        try {
            new VentanaGestionCompleta(co).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void etiquetaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etiquetaUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etiquetaUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem accionColabora;
    private javax.swing.JButton buttonConfirmar;
    private javax.swing.JMenu casosMenu;
    private javax.swing.JMenu conexion;
    private javax.swing.JPasswordField etiquetaPassword;
    private java.awt.TextField etiquetaUsuario;
    private javax.swing.JMenu expertoMenu;
    private javax.swing.JMenu gestionCompleta;
    private javax.swing.JMenuItem itemExperto;
    private javax.swing.JMenuItem itemSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuVerCasos;
    private javax.swing.JMenu menuColaboracion;
    // End of variables declaration//GEN-END:variables
}
